### ISSUE TITLE
Error code 2: iPhone user after scanning passport, it wont finalise account

### ISSUE THREAD

**Issue by DavidGiraldoCode** [Freja-eID/frejaeidclient#139]
**Describe the bug**
After successfully scanning the passport, on the Build your eID view, when pressing "Finalize Account" It yields `Error code : 2`

**To Reproduce**
Steps to reproduce the behavior: Follow the passport scanning progress, and after it scans, try to finalize.

**Expected behavior**
I do not know. I am trying to share my data with the migration

**Screenshots**
![IMG_39D35FFFFC9B-1](https://github.com/Freja-eID/frejaeidclient/assets/147272329/25cd02df-5c4d-4557-963e-6df7463be7b2)

**Smartphone (please complete the following information):**
 - iPhone 13 Pro max
 - iOS 16.2
 - Native App

**Comment by mirkostojmenovic-frejaeid** [comment]
Hello,

We appologize for the late response, did you managed to register in the meantime?
This is the github repo related to our Java client that we offer to other relying parties that are integrating with us.
If you still need assistance with registration, please free to contact us, our [support page](https://frejaeid.com/en/support/) on our website has all the info that you need.
